/*Autores: Lucas Emanuel Michaelsen, Gustavo Vítor Gaida e Mauro Pellizzaro
    Data:    04/12/2023
    FIESC:SENAI*/
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.ManutencoesDAO;

/**
 *
 * @author Professor
 */
public class Manutencao extends javax.swing.JFrame {

    /**
     * Creates new form Manutencao
     */
    public Manutencao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        controleManutencao = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Btn_filtrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Chk_aberto = new javax.swing.JCheckBox();
        Chk_finalizaddo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        Chk_estoque = new javax.swing.JCheckBox();
        Chk_processo = new javax.swing.JCheckBox();
        Chk_montagem = new javax.swing.JCheckBox();
        Chk_expedicao = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Geral Manutenções");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        controleManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Localização", "Observação", "Data de Inicio", "Data de Finalização", "Status", "HorasDeclaradas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(controleManutencao);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Filtros")));

        jButton3.setText("Mostrar Todos");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        Btn_filtrar.setText("Filtrar");
        Btn_filtrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_filtrarMouseClicked(evt);
            }
        });
        Btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_filtrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        Chk_aberto.setText("Em Aberto");
        Chk_aberto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Chk_abertoMouseDragged(evt);
            }
        });
        Chk_aberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_abertoMouseClicked(evt);
            }
        });

        Chk_finalizaddo.setText("Finalizadas");
        Chk_finalizaddo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_finalizaddoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chk_finalizaddo)
            .addComponent(Chk_aberto)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Chk_finalizaddo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Chk_aberto)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Setores"));

        Chk_estoque.setText("Estoque");
        Chk_estoque.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chk_estoqueStateChanged(evt);
            }
        });
        Chk_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_estoqueMouseClicked(evt);
            }
        });

        Chk_processo.setText("Processo");
        Chk_processo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chk_processoStateChanged(evt);
            }
        });
        Chk_processo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_processoMouseClicked(evt);
            }
        });

        Chk_montagem.setText("Montagem");
        Chk_montagem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chk_montagemStateChanged(evt);
            }
        });
        Chk_montagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_montagemMouseClicked(evt);
            }
        });

        Chk_expedicao.setText("Expedição");
        Chk_expedicao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chk_expedicaoStateChanged(evt);
            }
        });
        Chk_expedicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_expedicaoMouseClicked(evt);
            }
        });
        Chk_expedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chk_expedicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Chk_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Chk_processo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Chk_expedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Chk_montagem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_estoque)
                    .addComponent(Chk_processo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_expedicao)
                    .addComponent(Chk_montagem))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Btn_filtrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jButton1.setText("Adicionar Manutenção");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir Todas");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Excluir Selecionada");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Finalizar Manunteção Selecionada");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(5, 5, 5)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7))
        );

        jLabel3.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 24)); // NOI18N
        jLabel3.setText("MANUTENÇÕES");

        jLabel4.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 24)); // NOI18N
        jLabel4.setText("CONTROLE DE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(258, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        CadManutencao cadaux = new CadManutencao();
        cadaux.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    public void povoarJtable() {
        //criação de uma variavel modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) controleManutencao.getModel();
        //abre a tabela com 0 linhas quando n houver itens
        modelo.setNumRows(0);

        ManutencoesDAO mdao = new ManutencoesDAO();

        ManutencoesDAO manutencaodao = new ManutencoesDAO();
        //enquanto tiver alguma coisa na busca do get ele vai rpetir esse comando
        for (model.Manutencao m : mdao.getManutencao()) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getDescricao(),
                m.getLocalizacao(),
                m.getObservacao(),
                m.getData_inicio(),
                m.getData_fim(),
                m.getStatus(),
                m.getHorasdeclaradas()

            });
        }

    }

    public void povoarJtableFiltro(String comandoSQL) {
        //criação de uma variavel modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) controleManutencao.getModel();
        //abre a tabela com 0 linhas quando n houver itens
        modelo.setNumRows(0);

        ManutencoesDAO mdao = new ManutencoesDAO();

        ManutencoesDAO manutencaodao = new ManutencoesDAO();
        //enquanto tiver alguma coisa na busca do get ele vai rpetir esse comando
        for (model.Manutencao m : mdao.getFiltrar(comandoSQL)) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getDescricao(),
                m.getLocalizacao(),
                m.getObservacao(),
                m.getData_inicio(),
                m.getData_fim(),
                m.getStatus(),
                m.getHorasdeclaradas()

            });
        }

    }


    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        int opc = JOptionPane.showConfirmDialog(null, "Deseja Continuar");
        if (opc == 0) {
            ManutencoesDAO manExcluiTudo = new ManutencoesDAO();
            manExcluiTudo.ExcluiTudo();
            povoarJtable();
        };
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        ManutencoesDAO manExclui = new ManutencoesDAO();

        int selectedRow = controleManutencao.getSelectedRow();
        if (selectedRow != -1 && selectedRow < controleManutencao.getRowCount()) {
            Object value = controleManutencao.getValueAt(selectedRow, 0);

            if (value != null && value instanceof Integer) {
                int id = (int) value;
                manExclui.removeById(id);
                povoarJtable();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma manutenção para excluir");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma manutenção para excluir");
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        ManutencoesDAO manFinaliza = new ManutencoesDAO();
        float horas = 0.0f;

        int selectedRow = controleManutencao.getSelectedRow();
        if (selectedRow != -1 && selectedRow < controleManutencao.getRowCount()) {
            Object value = controleManutencao.getValueAt(selectedRow, 0);

            if (value != null && value instanceof Integer) {
                int id = (int) value;
                horas = Float.parseFloat(JOptionPane.showInputDialog("Informe a quantidade de horas trabalhadas"));
                manFinaliza.updateData_fim(id, horas);
                povoarJtable();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma manutenção para finalizar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma manutenção para finalizar");
        }
    }//GEN-LAST:event_jButton8MouseClicked


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        povoarJtable();
    }//GEN-LAST:event_formWindowOpened

    private void Chk_estoqueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chk_estoqueStateChanged

    }//GEN-LAST:event_Chk_estoqueStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        povoarJtable();
    }//GEN-LAST:event_jButton3MouseClicked

    private void Chk_processoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chk_processoStateChanged

    }//GEN-LAST:event_Chk_processoStateChanged

    private void Chk_expedicaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chk_expedicaoStateChanged

    }//GEN-LAST:event_Chk_expedicaoStateChanged

    private void Chk_montagemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chk_montagemStateChanged

    }//GEN-LAST:event_Chk_montagemStateChanged

    private void Btn_filtrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_filtrarMouseClicked
        String ComandoSQL;
        ManutencoesDAO manFiltra = new ManutencoesDAO();

        if (Chk_estoque.isSelected() && !Chk_aberto.isSelected() && !Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Estoque'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_processo.isSelected() && !Chk_aberto.isSelected() && !Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Processo'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_expedicao.isSelected() && !Chk_aberto.isSelected() && !Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Expedicao'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_montagem.isSelected() && !Chk_aberto.isSelected() && !Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Montagem'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_estoque.isSelected() && Chk_aberto.isSelected()) {
            System.out.println("Funcionou");
            ComandoSQL = "select * from manutencoes where localizacao = 'Estoque' and status = 'Em Aberto'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_estoque.isSelected() && Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Estoque' and status = 'Finalizada'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_processo.isSelected() && Chk_aberto.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Processo' and status = 'Em Aberto'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_processo.isSelected() && Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Processo' and status = 'Finalizada'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_expedicao.isSelected() && Chk_aberto.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Expedição' and status = 'Em Aberto'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_expedicao.isSelected() && Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Expedição' and status = 'Finalizada'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_montagem.isSelected() && Chk_aberto.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Montagem' and status = 'Em Aberto'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_montagem.isSelected() && Chk_finalizaddo.isSelected()) {
            ComandoSQL = "select * from manutencoes where localizacao = 'Montagem' and status = 'Finalizada'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_aberto.isSelected() && !Chk_finalizaddo.isSelected() && !Chk_estoque.isSelected() && !Chk_processo.isSelected() && !Chk_expedicao.isSelected() && !Chk_montagem.isSelected()) {
            ComandoSQL = "select * from manutencoes where status = 'Em Aberto'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        } else if (Chk_finalizaddo.isSelected() && !Chk_aberto.isSelected() && !Chk_estoque.isSelected() && !Chk_processo.isSelected() && !Chk_expedicao.isSelected() && !Chk_montagem.isSelected()) {
            ComandoSQL = "select * from manutencoes where status = 'Finalizada'";
            manFiltra.getFiltrar(ComandoSQL);
            povoarJtableFiltro(ComandoSQL);
        }

    }//GEN-LAST:event_Btn_filtrarMouseClicked

    private void Chk_estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_estoqueMouseClicked
        Chk_expedicao.setSelected(false);
        Chk_processo.setSelected(false);
        Chk_montagem.setSelected(false);
    }//GEN-LAST:event_Chk_estoqueMouseClicked

    private void Chk_processoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_processoMouseClicked
        Chk_expedicao.setSelected(false);
        Chk_estoque.setSelected(false);
        Chk_montagem.setSelected(false);
    }//GEN-LAST:event_Chk_processoMouseClicked

    private void Chk_expedicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_expedicaoMouseClicked
        Chk_estoque.setSelected(false);
        Chk_processo.setSelected(false);
        Chk_montagem.setSelected(false);
    }//GEN-LAST:event_Chk_expedicaoMouseClicked

    private void Chk_montagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_montagemMouseClicked
        Chk_expedicao.setSelected(false);
        Chk_processo.setSelected(false);
        Chk_estoque.setSelected(false);
    }//GEN-LAST:event_Chk_montagemMouseClicked

    private void Chk_expedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chk_expedicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chk_expedicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_filtrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_filtrarActionPerformed

    private void Chk_finalizaddoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_finalizaddoMouseClicked
        Chk_aberto.setSelected(false);
    }//GEN-LAST:event_Chk_finalizaddoMouseClicked

    private void Chk_abertoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_abertoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Chk_abertoMouseDragged

    private void Chk_abertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_abertoMouseClicked
        Chk_finalizaddo.setSelected(false);
    }//GEN-LAST:event_Chk_abertoMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        povoarJtable();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_filtrar;
    private javax.swing.JCheckBox Chk_aberto;
    private javax.swing.JCheckBox Chk_estoque;
    private javax.swing.JCheckBox Chk_expedicao;
    private javax.swing.JCheckBox Chk_finalizaddo;
    private javax.swing.JCheckBox Chk_montagem;
    private javax.swing.JCheckBox Chk_processo;
    private javax.swing.JTable controleManutencao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
